version: '3.8'

services:
  music-generator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_USER=music_service_user
      - DB_PASSWORD=TERRA85x5.
      - DB_NAME=music_service
      - DB_PORT=5432
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - OUTPUT_DIR=/app/output
    volumes:
      - ./output:/app/output
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=music_service
      - POSTGRES_USER=music_service_user
      - POSTGRES_PASSWORD=TERRA85x5.
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music_service_user -d music_service"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: