[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 60  # Интервал проверки в секундах
healthcheckMaxRetries = 3  # Количество попыток перед рестартом
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10